Домашнее задание 3. Телефонная книга
DaniarFF/CSharpEducation pull request #2
Opened 2024-08-11 15:08 UTC by DaniarFF

2024-08-11 17:41 UTC, yaporyvaev requested changes

2024-08-11 17:41 UTC, yaporyvaev commented on PhoneBook/AbonentList.cs
> +        public List<Abonent> Abonent { get; set; }
Назвать Abonents. У тебя же список

2024-08-11 17:41 UTC, yaporyvaev commented on PhoneBook/AbonentList.cs
> +        [JsonPropertyName("abonents")]
Настроить через конвеншены, убрать атрибуты

2024-08-11 17:41 UTC, yaporyvaev commented on PhoneBook/AbonentList.cs
> +        [JsonPropertyName("name")]
Убрать атрибут

2024-08-11 17:41 UTC, yaporyvaev commented on PhoneBook/PhoneBookClient.cs
> +using static System.Runtime.InteropServices.JavaScript.JSType;
Для чего это? Надо убрать

2024-08-11 17:41 UTC, yaporyvaev commented on PhoneBook/PhoneBookClient.cs
> +using System.Xml.Linq;
Откуда xml?

2024-08-11 17:41 UTC, yaporyvaev commented on PhoneBook/PhoneBookClient.cs
> +        PhoneBookRepository phoneBookRepository = new PhoneBookRepository();
Явно указать модификатор доступа. Приватные поля класса начинаются с "_", например "_phoneBookRepository".
Сделать инициализацию через конструктор

2024-08-11 17:41 UTC, yaporyvaev commented on PhoneBook/PhoneBookClient.cs
> +    public class PhoneBookClient
Почему класс называется Client? Client'ами называются классы, которые обращаются во внешние системы. В твоем случае это PhoneBookService

2024-08-11 17:41 UTC, yaporyvaev commented on PhoneBook/PhoneBookClient.cs
> +        public async Task GetAllAbonents(string path)
Сервис не должен принимать путь до файла. Сервис ничего не должен знать о доступе к данным, это ответственность DAL - слоя доступа к данным. В твоем сценарии, это репозиторий, хоть он и не выделен в отдельный слой

2024-08-11 17:41 UTC, yaporyvaev commented on PhoneBook/PhoneBookClient.cs
> +                Console.WriteLine("Что то пошло не так:( ");
Что-то*

2024-08-11 17:41 UTC, yaporyvaev commented on PhoneBook/PhoneBookClient.cs
> +        public async Task CreateNewAbonent(string path, AbonentList abonentList)
Убрать path

2024-08-11 17:41 UTC, yaporyvaev commented on PhoneBook/PhoneBookClient.cs
> +        public async Task CreateNewAbonent(string path, AbonentList abonentList)
Метод называется "Создать нового абонента", но принимает список абонентов, сделать название более релевантным, либо исправить параметры

2024-08-11 17:41 UTC, yaporyvaev commented on PhoneBook/PhoneBookClient.cs
> +                    Console.WriteLine($"Имя: {item.Name} Телефон: {item.PhoneNumber}");
Класс Console разрешается использовать только в Program.cs. Представь, что твой сервис и репозиторий, находится не в консольном приложении, а в библиотеке. В библиотеке нет консоли, соответственно ты не сможешь её вызвать. По хорошему, у тебя классы PhoneBookClient и PhoneBookRepository должны быть в разных проектах

2024-08-11 17:41 UTC, yaporyvaev commented on PhoneBook/PhoneBookClient.cs
> +                Console.WriteLine("Что то пошло не так:( ");
Убрать консоль

2024-08-11 17:41 UTC, yaporyvaev commented on PhoneBook/PhoneBookClient.cs
> +                Console.WriteLine("Напиши имя: ");
Убрать консоль

2024-08-11 17:41 UTC, yaporyvaev commented on PhoneBook/PhoneBookClient.cs
> +                    if(number < 0 || number > 1000000000000) { Console.WriteLine("Неверное кол - во цифр"); } //лень было обрабатывать формат, надеюсь не нужно было
Если номер будет начинаться со знака "+", упадёт. Подумать как еще сделать валидацию

2024-08-11 17:41 UTC, yaporyvaev commented on PhoneBook/PhoneBookClient.cs
> +        public async Task CreateNewAbonent(string path, AbonentList abonentList)
Зачем здесь abonentList?

2024-08-11 17:41 UTC, yaporyvaev commented on PhoneBook/PhoneBookClient.cs
> +        public async Task CreateNewAbonent(string path, AbonentList abonentList)
Данные об абоненте должны приходить в параметрах

2024-08-11 17:41 UTC, yaporyvaev commented on PhoneBook/PhoneBookClient.cs
> +        public async Task DeleteAbonent( string path, AbonentList abonentList)
Убрать параметры. Принимать данные для удаления

2024-08-11 17:41 UTC, yaporyvaev commented on PhoneBook/PhoneBookClient.cs
> +                Console.WriteLine("Напиши имя: ");
Убрать консоль

2024-08-11 17:41 UTC, yaporyvaev commented on PhoneBook/PhoneBookClient.cs
> +                await phoneBookRepository.DeleteAbonent(name, path, abonentList);
Передавать только идентификатор, по которому удалять

2024-08-11 17:41 UTC, yaporyvaev commented on PhoneBook/PhoneBookClient.cs
> +                Console.WriteLine("Что то пошло не так:( ");
Консоль

2024-08-11 17:41 UTC, yaporyvaev commented on PhoneBook/PhoneBookClient.cs
> +        public async Task FindAbonent(string path, AbonentList abonentList)
Убрать параметры, принимать идентификатор для поиска

2024-08-11 17:41 UTC, yaporyvaev commented on PhoneBook/PhoneBookClient.cs
> +            Console.WriteLine("Напиши имя или телефон");
Консоль

2024-08-11 17:41 UTC, yaporyvaev commented on PhoneBook/PhoneBookClient.cs
> +            if (int.TryParse(name, out int number))  // Возможа ли такая обработка? Или это бред
Если хочешь удаление по фио и по телефону -- сделай 2 разных метода

2024-08-11 17:41 UTC, yaporyvaev commented on PhoneBook/PhoneBookRepository.cs
> +        public async Task<AbonentList> GetAllAbonents(string path)
Не принимать path извне

2024-08-11 17:41 UTC, yaporyvaev commented on PhoneBook/PhoneBookRepository.cs
> +            using (FileStream fs = new FileStream(path, FileMode.OpenOrCreate))
using в новых шарпах можно упросить

2024-08-11 17:41 UTC, yaporyvaev commented on PhoneBook/PhoneBookRepository.cs
> +            Abonent newAbonent = new Abonent()
Можно принимать сразу Abontent

2024-08-11 17:41 UTC, yaporyvaev commented on PhoneBook/PhoneBookRepository.cs
> +            if(FindAbonent(name, path, abonentList).Result == null)
.Result?

2024-08-11 17:41 UTC, yaporyvaev commented on PhoneBook/PhoneBookRepository.cs
> +                Console.WriteLine("Абонент уже существует");
Консоль

2024-08-11 17:41 UTC, yaporyvaev commented on PhoneBook/PhoneBookRepository.cs
> +            abonentList.Abonent.Remove(itemToDelete);
FirstOrDefault может вернуть null. Нужна проверка перед удалением

2024-08-11 17:41 UTC, yaporyvaev commented on PhoneBook/PhoneBookRepository.cs
> +                Console.WriteLine($"Абонент {name} Удален");
Консоль

2024-08-11 17:41 UTC, yaporyvaev commented on PhoneBook/PhoneBookRepository.cs
> +        public async Task<Abonent> FindAbonent(string name, string path, AbonentList abonentList)
Если регистр аргумента и регистр строки в базе не совпадет, то не найдет получается

2024-08-11 17:41 UTC, yaporyvaev commented on PhoneBook/Program.cs
> +            string path = "C:\\Users\\Данияр\\source\\repos\\CSharpEducation\\PhoneBook\\PhoneBook.json";
Принимать из конфиг файла

2024-08-12 12:52 UTC, yaporyvaev requested changes

2024-08-12 12:52 UTC, yaporyvaev commented on .gitignore
> +/PhoneBook/App.config
Зачем конфиг в игнор добавил? Как человеку, который склонировал репозиторий запускать проект без этого файла?

2024-08-12 12:52 UTC, yaporyvaev commented on PhoneBook/Abonents.cs
> +    public class Abonent
Каждый класс в отдельный файл надо вынести

2024-08-12 12:52 UTC, yaporyvaev commented on PhoneBook/Abonents.cs
> +    public class Abonents
Не понимаю смысл этого класса

2024-08-12 12:52 UTC, yaporyvaev commented on PhoneBook/PhoneBookRepository.cs
> +        readonly string _filePath;
Модификатор доступа

2024-08-12 12:52 UTC, yaporyvaev commented on PhoneBook/PhoneBookRepository.cs
> +        JsonSerializerOptions options = new JsonSerializerOptions
Модификатор доступа. Приватное поле класса начинается с "_"

2024-08-12 12:52 UTC, yaporyvaev commented on PhoneBook/PhoneBookRepository.cs
> +            Abonents abonents = await JsonSerializer.DeserializeAsync<Abonents>(fs, options);
Можно просто десериализовать в List<Abonent> и не нужен будет бесполезный класс Abonents

2024-08-12 12:52 UTC, yaporyvaev commented on PhoneBook/PhoneBookRepository.cs
> +            if (await FindWithName(name) == null)
Лучше вынести вызов метода на отдельную строку

2024-08-12 12:52 UTC, yaporyvaev commented on PhoneBook/PhoneBookRepository.cs
> +            if (await FindWithName(name) == null)
FindByName, а не With

2024-08-12 12:52 UTC, yaporyvaev commented on PhoneBook/PhoneBookRepository.cs
> +                {
Зачем выбрасывать ошибку при удалении? Можно сказать что всё ок, т.к. записи не было, ничего не удалилось и никому при этом плохо не стало

2024-08-12 12:52 UTC, yaporyvaev commented on PhoneBook/PhoneBookRepository.cs
> +        public async Task<Abonent> FindWithNumber(string number)
FindByPhoneNumber

2024-08-12 12:52 UTC, yaporyvaev commented on PhoneBook/PhoneBookRepository.cs
> +        public string FirstLetterToUpperCase(string str)
Плохое название метода, нет глагола

2024-08-12 12:52 UTC, yaporyvaev commented on PhoneBook/PhoneBookRepository.cs
> +                var itemToDelete = abonents.Abonent.FirstOrDefault(s => s.Name == name);
Это не будет нормально работать. Если ты добавил изначально "ДАнияр", а потом пытаешься удалить "Данияр" у тебя будет ошибка

2024-08-12 12:52 UTC, yaporyvaev commented on PhoneBook/PhoneBookService.cs
> +        static string _filePath = ConfigurationManager.AppSettings["path"];
Обращение к файлу конфигурации не должно тут быть, только в корне приложения. Лучше принимать в конструкторе уже сконфигурированный PhoneBookRepository. Это называется Dependency Injection

2024-08-12 12:52 UTC, yaporyvaev commented on PhoneBook/PhoneBookService.cs
> +                throw new Exception(ex.Message);
Написал выше

2024-08-12 12:52 UTC, yaporyvaev commented on PhoneBook/PhoneBookService.cs
> +
Лишний пропуск строки

2024-08-12 12:52 UTC, yaporyvaev commented on PhoneBook/PhoneBookService.cs
> +                try
Достаточно одного блока try\catch на метод

2024-08-12 12:52 UTC, yaporyvaev commented on PhoneBook/PhoneBookService.cs
> +                throw new Exception(ex.Message);
Тебе уже приходит объект типа Exception извне, зачем ты создаешь новый? Если ты хочешь пробросить ошибку дальше, то можно просто написать throw;
И если ты ничего не делаешь в блоке catch, а только пробрасываешь исключение дальше, то try\catch можно вообще не писать

2024-08-12 12:52 UTC, yaporyvaev commented on PhoneBook/Program.cs
> +                if (await phoneBookService.AddNewAbonent(name, number))
Вынести вызов метода на отдельную строку

2024-08-12 12:52 UTC, yaporyvaev commented on PhoneBook/Program.cs
> +                if (await phoneBookService.DeleteAbonent(name))
Написал выше

2024-08-12 12:52 UTC, yaporyvaev commented on PhoneBook/PhoneBookService.cs
> +                    throw new Exception("Неправильный формат телефона, должен быть в формате +79998887766");
В этом кейсе неправильно использовать дефолтный Exception. По-хорошему, надо создать какой-нибудь ValidationException, унаследовать его от Exception и пользоваться им. Но нам пока пофиг

2024-08-12 12:52 UTC, yaporyvaev commented on PhoneBook/Program.cs
> +                Console.WriteLine(ex.Message);
В ex.Message может быть системный текст, непонятный пользователю, стоит его ему показывать?

2024-08-12 15:03 UTC, Dezodemius commented on PhoneBook/AbonentList.cs
> +        public List<Abonent> Abonent { get; set; }
реально

2024-08-12 15:22 UTC, Dezodemius requested changes

2024-08-12 15:22 UTC, Dezodemius commented on PhoneBook/Abonents.cs
> +    public class Abonent
и документацию добавить

2024-08-12 15:22 UTC, Dezodemius commented on PhoneBook/PhoneBook.csproj
> +  <ProjectExtensions><VisualStudio><UserProperties /></VisualStudio></ProjectExtensions>
шо это?

2024-08-12 15:22 UTC, Dezodemius commented on PhoneBook/PhoneBookRepository.cs
> +        JsonSerializerOptions options = new JsonSerializerOptions
по нашему соглашению не начинается

2024-08-12 15:22 UTC, Dezodemius commented on PhoneBook/PhoneBook.json
Для тестов можно и коммитить, но такое лучше не стоит в репозиторий добавлять

2024-08-12 15:22 UTC, Dezodemius commented on PhoneBook/PhoneBookRepository.cs
> +        public PhoneBookRepository(string path)
По соглашению нужно конструктор в конце файла ставить

2024-08-12 15:22 UTC, Dezodemius commented on PhoneBook/PhoneBookRepository.cs
> +        public PhoneBookRepository(string path)
Кажется, лучше чтоб имя и путь к файлу были внутри зашиты. Чтоб снаружи никто не знал про него так просто

2024-08-12 15:22 UTC, Dezodemius commented on PhoneBook/PhoneBookRepository.cs
> +            using FileStream fs = new FileStream(_filePath, FileMode.OpenOrCreate);
Я бы в конструкторе это делал. А getAll пусть просто возвращает все элементы из abonents

2024-08-12 15:22 UTC, Dezodemius commented on PhoneBook/PhoneBookRepository.cs
> +        public async Task AddNew(string name, string number)
Можно просто Add

2024-08-12 15:22 UTC, Dezodemius commented on PhoneBook/PhoneBookRepository.cs
> +            Abonents abonents = await GetAll();
было б проще коллекцию завести в классе и к ней обращаться, чтоб каждый раз в файл не записывать

2024-08-12 15:22 UTC, Dezodemius commented on PhoneBook/PhoneBookRepository.cs
> +        public async Task AddNew(string name, string number)
а чё он async? Зачем?

2024-08-12 15:22 UTC, Dezodemius commented on PhoneBook/PhoneBookRepository.cs
> +                throw new Exception("Абонент уже существует");
ну будто бы какое-то получше исключение подобрать надо. А то Exception слишком жирно

2024-08-12 15:22 UTC, Dezodemius commented on PhoneBook/PhoneBookRepository.cs
> +        public string FirstLetterToUpperCase(string str)
а нафиг он нужон вообще? Метод этот. Вот как пользователя назвали, так пусть и добавляет

2024-08-12 15:22 UTC, Dezodemius commented on PhoneBook/PhoneBookRepository.cs
> +        public async Task Delete(string name)
а если у тебя будет 10 Егоров в абонентах, то все удалятся? Я бы привязывался к номеру телефона, а не к имени. Потому что у номер один владелец только может быть

2024-08-22 19:47 UTC, yaporyvaev requested changes

2024-08-22 19:47 UTC, yaporyvaev commented on .gitignore
> +/PhoneBook/App.config
????????????????????????????

2024-08-22 19:47 UTC, yaporyvaev commented on PhoneBook/Models/Abonent.cs
> +        public string Name { get; set; }
Комментарий

2024-08-22 19:47 UTC, yaporyvaev commented on PhoneBook/PhoneBook.json
> +[
Не надо этот файл в репозиторий добавлять мне кажется

2024-08-22 19:47 UTC, yaporyvaev commented on PhoneBook/PhoneBookRepository.cs
> +    #region Поля и свойства
втф

2024-08-22 19:47 UTC, yaporyvaev commented on PhoneBook/PhoneBookRepository.cs
> +    #region Вложенные типы
сейм

2024-08-22 19:47 UTC, yaporyvaev commented on PhoneBook/PhoneBookRepository.cs
> +    JsonSerializerOptions options = new JsonSerializerOptions()
Модификатор доступа

2024-08-22 19:47 UTC, yaporyvaev commented on PhoneBook/PhoneBookRepository.cs
> +      Abonent abonent = await FindByName(name);
Тёзки лесом идут?

2024-08-22 19:47 UTC, yaporyvaev commented on PhoneBook/PhoneBookRepository.cs
> +        throw new InvalidOperationException("Абонент уже существует");
Дефолтные эксепшены не принято выкидывать в любой непонятной ситуации, тут лучше свой эксепшен сделать

2024-08-22 19:47 UTC, yaporyvaev commented on PhoneBook/PhoneBookRepository.cs
> +        var itemToDelete = abonents.FirstOrDefault(s => s.Name == name);
Шо если у людей имя одинаковое?

2024-08-22 19:47 UTC, yaporyvaev commented on PhoneBook/PhoneBookRepository.cs
> +        throw new Exception("Ошибка удаления");
Не нравится. Ты ничего не делаешь в блоке catch полезного. Наоборот, ты перетираешь исходный объект, в котором была вся информация об ошибке, не надо так

2024-08-22 19:47 UTC, yaporyvaev commented on PhoneBook/PhoneBookRepository.cs
> +    public async Task<Abonent> FindByName(string name)
Как будто по имени может найтись несколько контактов

2024-08-22 19:47 UTC, yaporyvaev commented on PhoneBook/PhoneBookRepository.cs
> +    public string CapitalizeFirstLetter(string str)
В чем прекол этого метода?

2024-08-22 19:47 UTC, yaporyvaev commented on PhoneBook/PhoneBookService.cs
> +    private string filePath;
Не нужно здесь

2024-08-22 19:47 UTC, yaporyvaev commented on PhoneBook/PhoneBookService.cs
> +    public async Task<List<Abonent>> GetAllAbonents()
Асинк авейт не нужен

2024-08-22 19:47 UTC, yaporyvaev commented on PhoneBook/PhoneBookService.cs
> +        throw new Exception("Неправильный формат телефона, должен быть в формате +79998887766");
ValidationException должен быть

2024-08-22 19:47 UTC, yaporyvaev commented on PhoneBook/PhoneBookService.cs
> +        throw new Exception("Неправильный формат телефона, должен быть в формате +79998887766");
Вообще плохо строить логику на эксепшенах, но это нам пока не важно, просто держи в голове

2024-08-22 19:47 UTC, yaporyvaev commented on PhoneBook/PhoneBookService.cs
> +        return true;
Зачем тут bool результат?

2024-08-22 19:47 UTC, yaporyvaev commented on PhoneBook/PhoneBookService.cs
> +      return true;
Зачем bool результат?

2024-08-22 19:47 UTC, yaporyvaev commented on PhoneBook/Program.cs
> +      IServiceCollection services = new ServiceCollection();
А тут шо регионы свои бесполезные не воткнул

2024-08-22 19:47 UTC, yaporyvaev commented on PhoneBook/Program.cs
> +    static async Task GetAllAbonents(IPhoneBookService phoneBookService)
модификатор доступа

2024-08-22 19:47 UTC, yaporyvaev commented on PhoneBook/Program.cs
> +    static async Task GetAllAbonents(IPhoneBookService phoneBookService)
Аргумент лучше вынести в поле

2024-08-22 19:47 UTC, yaporyvaev commented on PhoneBook/Program.cs
> +        List<Abonent> list = await phoneBookService.GetAllAbonents();
Если с типами данных, объявлением и инциализацией переменных разобрался, используй var, если понимаешь шо это такое и как работает

2024-08-22 19:47 UTC, yaporyvaev commented on PhoneBook/Program.cs
> +    static async Task AddNew(IPhoneBookService phoneBookService)
модификатор доступа

2024-08-22 19:47 UTC, yaporyvaev commented on PhoneBook/Settings/App.config
> +﻿<?xml version="1.0" encoding="utf-8" ?>
Что за файл, зачем он?

2024-08-22 19:47 UTC, yaporyvaev commented on PhoneBook/Settings/ApplicationSettings.cs
> +    public ApplicationSettings(string repositoryPath)
Конфиг файлам не нужен конструктор

2024-08-23 18:21 UTC, yaporyvaev requested changes

2024-08-23 18:21 UTC, yaporyvaev commented on .gitignore
> +/PhoneBook/App.config
Удоли

2024-08-23 18:21 UTC, yaporyvaev commented on PhoneBook/Exceptions/ContactAlreadyExistsException.cs
> +  public class ContactAlreadyExistsException : ApplicationException
Слишком конкретизировал. Достаточно сделать общий ValidationException

2024-08-23 18:21 UTC, yaporyvaev commented on PhoneBook/Exceptions/ContactDoesntExistException.cs
> +  public class ContactDoesntExistException : ApplicationException
Соответственно этот уже не нужен

2024-08-23 18:21 UTC, yaporyvaev commented on PhoneBook/Exceptions/InvalidPhoneNumberFormatException.cs
> +    public InvalidPhoneNumberFormatException(string message) : base(message)
Тоже не нужен

2024-08-23 18:21 UTC, yaporyvaev commented on PhoneBook/PhoneBookRepository.cs
> +      try
Что даёт тебе блок trycatch в этом случае?

2024-08-23 18:21 UTC, yaporyvaev commented on PhoneBook/PhoneBookRepository.cs
> +      try
Писал выше

2024-08-23 18:21 UTC, yaporyvaev commented on PhoneBook/PhoneBookRepository.cs
> +        foreach (var item in contacts)
Зачем цикл?

2024-08-23 18:21 UTC, yaporyvaev commented on PhoneBook/PhoneBookRepository.cs
> +          if (item.PhoneNumber == contact.PhoneNumber)
Если из аргумента используешь только телефон, зачем передавал целый объект?

2024-08-23 18:21 UTC, yaporyvaev commented on PhoneBook/PhoneBookRepository.cs
> +            contact = item;
Переписывать аргумент метода это вообще смерть. Это ссылочный тип, если ты его перепишешь здесь, он у тебя изменится там, откуда ты его передавал и можно вообще в ногу себе выстрелить, если не делаешь это специально

2024-08-23 18:21 UTC, yaporyvaev commented on PhoneBook/PhoneBookRepository.cs
> +    public async Task Delete(Contact contact)
Я бы предложил пересмотреть реализацию этого метода

2024-08-23 18:21 UTC, yaporyvaev commented on PhoneBook/PhoneBookService.cs
> +      Regex regex = new Regex(@"^\+7\d{10}$");
Лучше опустить ниже по коду, к использованию. Создаешь объект, который может никогда не использоваться

2024-08-23 18:21 UTC, yaporyvaev commented on PhoneBook/PhoneBookService.cs
> +        return default;
Шо за дефолт

2024-08-23 18:21 UTC, yaporyvaev commented on PhoneBook/PhoneBookService.cs
> +    {
Форматирование поправить

2024-08-23 18:21 UTC, yaporyvaev commented on PhoneBook/Program.cs
> +      var cfg = new ConfigurationBuilder().AddJsonFile("config.json").Build();
Где сам файл конфига? Его нет в репо

2024-08-23 18:21 UTC, yaporyvaev commented on PhoneBook/Program.cs
> +      var cfg = new ConfigurationBuilder().AddJsonFile("config.json").Build();
Этот файл обычно называется appsettings.json

2024-08-29 10:06 UTC, merged